/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.0
 * Generated at: 2019-07-04 08:32:40 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.carOfficial;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class booking_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP 只允许 GET、POST 或 HEAD。Jasper 还允许 OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=utf-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE HTML>\r\n");
      out.write("<html>\r\n");
      out.write("\r\n");
      out.write("\t<head>\r\n");
      out.write("\t\t<meta name=\"renderer\" content=\"webkit\">\r\n");
      out.write("\t\t<meta charset=\"utf-8\" />\r\n");
      out.write("\t\t<meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge,chrome=1\">\r\n");
      out.write("\t\t<title>最强汽修有限公司</title>\r\n");
      out.write("\r\n");
      out.write("\t\t<link rel=\"stylesheet\" type=\"text/css\" href=\"./css/meteinfo_ui.css\" id=\"metuimodule\" data-module=\"1\" />\r\n");
      out.write("\t\t<link rel=\"stylesheet\" type=\"text/css\" href=\"./css/metinfo.css\" />\r\n");
      out.write("\t\t<script src=\"./js/jQuery1.7.2.js\" type=\"text/javascript\"></script>\r\n");
      out.write("\t\t<script src=\"./js/metinfo_ui.js\" type=\"text/javascript\"></script>\r\n");
      out.write("\t\t<script src=\"./js/ch.js\" type=\"text/javascript\"></script>\r\n");
      out.write("\t\t<!--[if IE]>\r\n");
      out.write("<script src=\"./public/js/html5.js\" type=\"text/javascript\"></script>\r\n");
      out.write("<![endif]-->\r\n");
      out.write("\t</head>\r\n");
      out.write("\r\n");
      out.write("\t<body>\r\n");
      out.write("\t\t<div class=\"m-nav\">\r\n");
      out.write("\t\t<nav class=\"inner\">\r\n");
      out.write("\t\t\t<ul class=\"list-none\">\r\n");
      out.write("\t\t\t\t<li id=\"nav_10001\" style='width: 123px;' class='navdown'><a\r\n");
      out.write("\t\t\t\t\thref=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/indexUrl?op=queryBunner\" title='网站首页' class='nav'><span>网站首页</span></a></li>\r\n");
      out.write("\t\t\t\t<li id='nav_1' style='width: 123px;'><a \r\n");
      out.write("\t\t\t\t\t0 title='关于我们' class='hover-none nav'><span>关于我们</span></a></li>\r\n");
      out.write("\t\t\t\t<li id='nav_2' style='width: 123px;'><a\r\n");
      out.write("\t\t\t\t\ttitle='信息中心' class='hover-none nav'><span>信息中心</span></a></li>\r\n");
      out.write("\t\t\t\t<li id='nav_3' style='width: 123px;'><a \r\n");
      out.write("\t\t\t\t\ttitle='恒达汽修产品' class='hover-none nav'><span>最强汽修产品</span></a></li>\r\n");
      out.write("\t\t\t\t<li id='nav_4' style='width: 122px;'><a href='");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/CarUrl?op=carservice'\r\n");
      out.write("\t\t\t\t\ttitle='服务车型' class='hover-none nav'><span>服务车型</span></a></li>\r\n");
      out.write("\t\t\t\t<li id='nav_34' style='width: 122px;'><a \r\n");
      out.write("\t\t\t\t\ttitle='在线招聘' class='hover-none nav'><span>在线招聘</span></a></li>\r\n");
      out.write("\t\t\t\t<li id='nav_11' style='width: 122px;'><a href='");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/carOfficial/booking.jsp'\r\n");
      out.write("\t\t\t\t\ttitle='在线预约' class='hover-none nav'><span>在线预约</span></a></li>\r\n");
      out.write("\t\t\t\t<li id='nav_18' style='width: 122px;'><a \r\n");
      out.write("\t\t\t\t\ttitle='联系我们' class='hover-none nav'><span>联系我们</span></a></li>\r\n");
      out.write("\t\t\t</ul>\r\n");
      out.write("\t\t</nav>\r\n");
      out.write("\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t<header>\r\n");
      out.write("\t\t\t<div class=\"inner top\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<a href=\"./../\" title=\"汽配公司\" id=\"web_logo\">\r\n");
      out.write("\t\t\t\t\t<img src=\"./img/1363847903.png\" style=\"width: 210px; height: 55px;\" alt=\"汽配公司\" title=\"汽配公司\" style=\"margin:0px 0px 0px 10px;\" />\r\n");
      out.write("\t\t\t\t</a>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<div class=\"top-seo\">\r\n");
      out.write("\t\t\t\t\t<div class=\"tpseotxt\">\r\n");
      out.write("\t\t\t\t\t\t<p>\r\n");
      out.write("\t\t\t\t\t\t\t&nbsp;020-5856-1762</p>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</header>\r\n");
      out.write("\r\n");
      out.write("\t\t<div class=\"inner met_flash\">\r\n");
      out.write("\t\t\t<div class=\"flash\">\r\n");
      out.write("\t\t\t\t<img src='img/1363850250.jpg' width='980' alt='' height='300'></div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t<div class=\"sidebar inner\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t<div class=\"sb_nav\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<h3 class='title line'>联系方式</h3>\r\n");
      out.write("\t\t\t\t<div class=\"active editor b-r\">\r\n");
      out.write("\t\t\t\t\t<div> 电话：020-5856-1762</div>\r\n");
      out.write("\t\t\t\t\t<div> 手机：15521389512</div>\r\n");
      out.write("\t\t\t\t\t<div> QQ：913405314</div>\r\n");
      out.write("\t\t\t\t\t<div> 联系人：谭先生</div>\r\n");
      out.write("\t\t\t\t\t<div> 邮箱：hengdaqixiu@163.com</div>\r\n");
      out.write("\t\t\t\t\t<div> 邮编：404100</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"clear\"></div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t<div class='sb_box b-r'>\r\n");
      out.write("\t\t\t\t<h3 class=\"title\">\r\n");
      out.write("\t\t\t<div class=\"position\">当前位置：<a href=\"./../\" title=\"网站首页\">网站首页</a> &gt; <a href=../feedback/ >在线预约</a></div>\r\n");
      out.write("\t\t\t<span>在线预约</span>\r\n");
      out.write("\t\t</h3>\r\n");
      out.write("\t\t\t\t<div class=\"clear\"></div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<div class=\"active\" id=\"feedback\">\r\n");
      out.write("\t\t\t\t\t<script language='javascript'>\r\n");
      out.write("\t\t\t\t\t\tfunction Checkfeedback() {\r\n");
      out.write("\t\t\t\t\t\t\tif (document.myform.para16.value.length == 0) {\r\n");
      out.write("\t\t\t\t\t\t\t\talert('详细说明 不能为空');\r\n");
      out.write("\t\t\t\t\t\t\t\tdocument.myform.para16.focus();\r\n");
      out.write("\t\t\t\t\t\t\t\treturn false;\r\n");
      out.write("\t\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t</script>\r\n");
      out.write("\t\t\t\t\t<form id=\"frmAddBooking\" action=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/QiantaiUrl?op=appAdd\" method='POST' name='myform'   target='_self'>\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t<span>");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${retMsg }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</span>\r\n");
      out.write("\t\t\t\t\t\t<table class='feedback_table'>\r\n");
      out.write("\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td class='text'>姓名:</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td class='input'><input maxlength=\"10\" name=\"userName\" type='text' size='30' class='input-text' /><span class='info' id=\"name\">*</span></td>\r\n");
      out.write("\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td class='text'>性别:</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td class='input'>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<input name='sex' type='radio' id='para18' value='男' checked='checked' />\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<label for='para18'>男</label> \r\n");
      out.write("\t\t\t\t\t\t\t\t\t<input name='sex' type='radio' id='para28' value='女' />\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<label for='para28'>女</label> \r\n");
      out.write("\t\t\t\t\t\t\t\t\t<span class='info' id=\"sex\"></span><span></span></td>\r\n");
      out.write("\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td class='text'>车牌:</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td class='input'><input maxlength=\"10\" name='carBrand' type='text' size='30' class='input-text' /><span class='info' id=\"licensePlateNumber\">*</span></td>\r\n");
      out.write("\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td class='text'>车型:</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td>&nbsp;&nbsp;\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<select style=\"width: 160spx;\" class=\"input\" name=\"carId\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<option value=\"1\">小型车</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<option value=\"2\">微型车</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<option value=\"3\">紧凑车型</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<option value=\"4\">CDV车型</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<option value=\"5\">MPV车型</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<option value=\"6\">SUV车型</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<option value=\"7\">三厢车型</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<option value=\"8\">豪华车型</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</select>\r\n");
      out.write("\t\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td class='text'>手机:</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td class='input'><input name=\"tel\" maxlength='11' type='text' size='30' class='input-text' /><span id=\"phone\" class='info'></span><span></span></td>\r\n");
      out.write("\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td class='text'>预约时间:</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td class='input'>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<input name=\"appointmentTime\"  type=\"datetime-local\"  /><span  class='info' id=\"appointmentTime\"></span>\r\n");
      out.write("\t\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td class='text'>服务类型:</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td>&nbsp;&nbsp;\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<select style=\"width: 160spx;\" class=\"input\" name=\"serviceId\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<option value=\"1\">&nbsp;&nbsp;修车</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<option value=\"2\">&nbsp;&nbsp;保养</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</select>\r\n");
      out.write("\t\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t<!-- <tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td class='text'>验证码</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td class='input'><input name='code' onKeyUp='pressCaptcha(this)' type='text' class='code'  size='6' maxlength='8' style='width:50px' />\r\n");
      out.write("\t\t\t\t\t\t\t\t<img align='absbottom' src='img/code.jpg' onclick=this.src='../member/ajax.php?action=code&' +Math.random()\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tstyle='cursor: pointer;' title='看不清？点击更换验证码' /><span id=\"code\" class=\"info\"></span></td>\r\n");
      out.write("\t\t\t\t\t\t\t</tr> -->\r\n");
      out.write("\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td class='text'></td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td class='submint'>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<input id=\"btnSubmit\" type=\"submit\" name='Submit' value='提交信息' class='submit button orange'>\r\n");
      out.write("\t\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t</table>\r\n");
      out.write("\t\t\t\t\t</form>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class=\"clear\"></div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div class=\"clear\"></div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t<footer class=\"inner\">\r\n");
      out.write("\t\t\t<div class=\"foot-nav\">\r\n");
      out.write("\t\t\t\t<a 0 title='关于我们'>关于我们</a><span> |</span> <a title='客户留言'>客户留言</a><span>|\r\n");
      out.write("\t\t\t\t\t<span> <a\r\n");
      out.write("\t\t\t\t\t\thref='");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/carOfficial/booking.jsp'\r\n");
      out.write("\t\t\t\t\t\ttitle='在线预约'>在线预约</a><span>| </span> <a title='人才招聘'>人才招聘</a><span>|\r\n");
      out.write("\t\t\t\t\t\t\t<a title='网站地图'>联系我们</a>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class=\"foot-text\">\r\n");
      out.write("\t\t\t\t<p>最强汽修有限公司版权所有 2017-2018 备案号：渝ICP备13004606</p>\r\n");
      out.write("\t\t\t\t<p>电话：020-5856-1762</p>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</footer>\r\n");
      out.write("\t<script type=\"text/javascript\" src=\"./js/jquery-3.2.1.min.js\" ></script>\r\n");
      out.write("\t\t<script type=\"text/javascript\">\r\n");
      out.write("\t\t\t$(function(){\r\n");
      out.write("\t\t\t\t$(\"#btnSubmit\").click(function(){\r\n");
      out.write("\t\t\t\t\tvar name=$(\"input[name=clientName]\").val();\r\n");
      out.write("\t\t\t\t\tvar phone=$(\"input[name=telephone]\").val();\r\n");
      out.write("\t\t\t\t\tvar appointmentTime=$(\"input[name=appointmentTime]\").val();\r\n");
      out.write("\t\t\t\t\tvar code=$(\"input[name=code]\").val();\r\n");
      out.write("\t\t\t\t\tvar licensePlateNumber=$(\"input[name=licensePlateNumber]\").val();\r\n");
      out.write("\t\t\t\t\t//alert(licensePlateNumber)\r\n");
      out.write("\t\t\t\t\tvar myreg = /^(((13[0-9]{1})|(15[0-9]{1})|(18[0-9]{1}))+\\d{8})$/; \r\n");
      out.write("\t\t\t\t\tif(name==\"\"){\r\n");
      out.write("\t\t\t\t\t\t$(\"#name\").text(\"请输入姓名\");\r\n");
      out.write("\t\t\t\t\t\treturn false; \r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t$(\"#name\").text(\"\");\r\n");
      out.write("\t\t\t\t\t/* if(!myreg.test(phone)) \r\n");
      out.write("\t\t\t\t\t{ \r\n");
      out.write("\t\t\t\t\t   $(\"#phone\").text(\"请输入有效的手机号码！\");\r\n");
      out.write("\t\t\t\t\t    return false; \r\n");
      out.write("\t\t\t\t\t}  $(\"#phone\").text(\"\"); */\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\tvar is= isVehicleNumber(licensePlateNumber);\r\n");
      out.write("\t\t\t\t\t/* if(!is){\r\n");
      out.write("\t\t\t\t\t\t$(\"#licensePlateNumber\").text(\"请输入正确的车牌号码\");\r\n");
      out.write("\t\t\t\t\t\treturn false;\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t$(\"#licensePlateNumber\").text(\"\"); */\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\tif(appointmentTime.length<3){\r\n");
      out.write("\t\t\t\t\t\t//alert(\"错\")\r\n");
      out.write("\t\t\t\t\t\t$(\"#appointmentTime\").text(\"请选择预约时间\");\r\n");
      out.write("\t\t\t\t\t\treturn false; \r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t$(\"#appointmentTime\").text(\"\");\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t/* if(code==\"\"){\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t$(\"#code\").text(\"请选择预约时间\");\r\n");
      out.write("\t\t\t\t\t\treturn false; \r\n");
      out.write("\t\t\t\t\t} */\r\n");
      out.write("\t\t\t\t\t$(\"#code\").text(\"\");\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t//可以提交\r\n");
      out.write("\t\t\t\t\t//$(\"#frmAddBooking\").submit();\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t})\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t});\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t//正则表达式验证车牌号码是否正确\r\n");
      out.write("\t\t\t  function isVehicleNumber(vehicleNumber) {\r\n");
      out.write("\t\t\t      var result = false;\r\n");
      out.write("\t\t\t      if (vehicleNumber.length == 7){\r\n");
      out.write("\t\t\t        var express = /^[京津沪渝冀豫云辽黑湘皖鲁新苏浙赣鄂桂甘晋蒙陕吉闽贵粤青藏川宁琼使领A-Z]{1}[A-Z]{1}[A-Z0-9]{4}[A-Z0-9挂学警港澳]{1}$/;\r\n");
      out.write("\t\t\t        result = express.test(vehicleNumber);\r\n");
      out.write("\t\t\t      }\r\n");
      out.write("\t\t\t      return result;\r\n");
      out.write("\t\t\t  }\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t</script>\r\n");
      out.write("\t</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
