/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.0
 * Generated at: 2019-07-04 07:38:23 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.backstage.inc;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class left_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP 只允许 GET、POST 或 HEAD。Jasper 还允许 OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=utf-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD XHTML 1.0 Transitional//EN\" \"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd\">\r\n");
      out.write("<html xmlns=\"http://www.w3.org/1999/xhtml\">\r\n");
      out.write("\r\n");
      out.write("\t<head>\r\n");
      out.write("\t\t<meta http-equiv=\"Content-Type\" content=\"text/html; charset=utf-8\" />\r\n");
      out.write("\t\t<title>首页左侧导航</title>\r\n");
      out.write("\t\t<link rel=\"stylesheet\" type=\"text/css\" href=\"../css/public.css\" />\r\n");
      out.write("\t\t<script type=\"text/javascript\" src=\"../js/jquery.min.js\"></script>\r\n");
      out.write("\t\t<script type=\"text/javascript\" src=\"../js/public.js\"></script>\r\n");
      out.write("\r\n");
      out.write("\t\t<head></head>\r\n");
      out.write("\r\n");
      out.write("\t\t<body id=\"bg\">\r\n");
      out.write("\t\t\t<!-- 左边节点 -->\r\n");
      out.write("\t\t\t<div class=\"container\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<div class=\"leftsidebar_box\">\r\n");
      out.write("\t\t\t\t\t<a href=\"../main.jsp\" target=\"main\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"line\">\r\n");
      out.write("\t\t\t\t\t\t\t<img src=\"../img/coin01.png\" />&nbsp;&nbsp;首页\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t\t<!-- <dl class=\"system_log\">\r\n");
      out.write("\t\t\t<dt><img class=\"icon1\" src=\"../img/coin01.png\" /><img class=\"icon2\"src=\"../img/coin02.png\" />\r\n");
      out.write("\t\t\t\t首页<img class=\"icon3\" src=\"../img/coin19.png\" /><img class=\"icon4\" src=\"../img/coin20.png\" /></dt>\r\n");
      out.write("\t\t</dl> -->\r\n");
      out.write("\t\t\t\t\t<dl class=\"system_log\">\r\n");
      out.write("\t\t\t\t\t\t<dt>\r\n");
      out.write("\t\t\t\t\t<img class=\"icon1\" src=\"../img/coin03.png\" /><img class=\"icon2\"\r\n");
      out.write("\t\t\t\t\t\tsrc=\"../img/coin04.png\" /> 轮播图管理<img class=\"icon3\"\r\n");
      out.write("\t\t\t\t\t\tsrc=\"../img/coin19.png\" /><img class=\"icon4\"\r\n");
      out.write("\t\t\t\t\t\tsrc=\"../img/coin20.png\" />\r\n");
      out.write("\t\t\t\t</dt>\r\n");
      out.write("\t\t\t\t\t\t<dd>\r\n");
      out.write("\t\t\t\t\t\t\t<img class=\"coin11\" src=\"../img/coin111.png\" /><img class=\"coin22\" src=\"../img/coin222.png\" />\r\n");
      out.write("\t\t\t\t\t\t\t<a class=\"cks\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/BanUrl?op=queryBanner\" target=\"main\" >图片列表</a><img class=\"icon5\" src=\"../img/coin21.png\" />\r\n");
      out.write("\t\t\t\t\t\t</dd>\r\n");
      out.write("\t\t\t\t\t</dl>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t<dl class=\"system_log\">\r\n");
      out.write("\t\t\t\t\t\t<dt>\r\n");
      out.write("\t\t\t\t\t<img class=\"icon1\" src=\"../img/coin07.png\" /><img class=\"icon2\"\r\n");
      out.write("\t\t\t\t\t\tsrc=\"../img/coin08.png\" />汽车类型管理<img class=\"icon3\"\r\n");
      out.write("\t\t\t\t\t\tsrc=\"../img/coin19.png\" /><img class=\"icon4\"\r\n");
      out.write("\t\t\t\t\t\tsrc=\"../img/coin20.png\" />\r\n");
      out.write("\t\t\t\t\t\t</dt>\r\n");
      out.write("\t\t\t\t\t\t<dd>\r\n");
      out.write("\t\t\t\t\t\t\t<img class=\"coin11\" src=\"../img/coin111.png\" />\r\n");
      out.write("\t\t\t\t\t\t\t<img class=\"coin22\" src=\"../img/coin222.png\" />\r\n");
      out.write("\t\t\t\t\t\t\t<a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/CarUrl?op=findall&name\" target=\"main\"  class=\"cks\">汽车列表</a>\r\n");
      out.write("\t\t\t\t\t\t\t<img class=\"icon5\" src=\"../img/coin21.png\" />\r\n");
      out.write("\t\t\t\t\t\t</dd>\r\n");
      out.write("\t\t\t\t\t</dl>\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t<dl class=\"system_log\">\r\n");
      out.write("\t\t\t\t\t\t<dt>\r\n");
      out.write("\t\t\t\t\t<img class=\"icon1\" src=\"../img/coin05.png\" /><img class=\"icon2\"\r\n");
      out.write("\t\t\t\t\t\tsrc=\"../img/coin06.png\" />库存配件管理<img class=\"icon3\"\r\n");
      out.write("\t\t\t\t\t\tsrc=\"../img/coin19.png\" /><img class=\"icon4\"\r\n");
      out.write("\t\t\t\t\t\tsrc=\"../img/coin20.png\" />\r\n");
      out.write("\t\t\t\t</dt>\r\n");
      out.write("\t\t\t\t\t\t<dd>\r\n");
      out.write("\t\t\t\t\t\t\t<img class=\"coin11\" src=\"../img/coin111.png\" /><img class=\"coin22\" src=\"../img/coin222.png\" />\r\n");
      out.write("\t\t\t\t\t\t\t<a class=\"cks\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/StoUrl?op=queryList\" target=\"main\" >库存物品</a><img class=\"icon5\" src=\"../img/coin21.png\" />\r\n");
      out.write("\t\t\t\t\t\t</dd>\r\n");
      out.write("\t\t\t\t\t</dl>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t</dl>\r\n");
      out.write("\t\t\t\t\t<dl class=\"system_log\">\r\n");
      out.write("\t\t\t\t\t\t<dt>\r\n");
      out.write("\t\t\t\t\t<img class=\"icon1\" src=\"../img/coin11.png\" /><img class=\"icon2\"\r\n");
      out.write("\t\t\t\t\t\tsrc=\"../img/coin12.png\" />预约管理<img class=\"icon3\"\r\n");
      out.write("\t\t\t\t\t\tsrc=\"../img/coin19.png\" /><img class=\"icon4\"\r\n");
      out.write("\t\t\t\t\t\tsrc=\"../img/coin20.png\" />\r\n");
      out.write("\t\t\t\t</dt>\r\n");
      out.write("\t\t\t\t\t\t<dd>\r\n");
      out.write("\t\t\t\t\t\t\t<img class=\"coin11\" src=\"../img/coin111.png\" /><img class=\"coin22\" src=\"../img/coin222.png\" />\r\n");
      out.write("\t\t\t\t\t\t\t<a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/AppUrl?op=queryCusInfo\" target=\"main\" class=\"cks\">预约列表</a><img class=\"icon5\" src=\"../img/coin21.png\" />\r\n");
      out.write("\t\t\t\t\t\t</dd>\r\n");
      out.write("\t\t\t\t\t</dl>\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t<dl class=\"system_log\">\r\n");
      out.write("\t\t\t\t\t\t<dt>\r\n");
      out.write("\t\t\t\t\t<img class=\"icon1\" src=\"../img/coin07.png\" /><img class=\"icon2\"\r\n");
      out.write("\t\t\t\t\t\tsrc=\"../img/coin08.png\" />新闻管理<img class=\"icon3\"\r\n");
      out.write("\t\t\t\t\t\tsrc=\"../img/coin19.png\" /><img class=\"icon4\"\r\n");
      out.write("\t\t\t\t\t\tsrc=\"../img/coin20.png\" />\r\n");
      out.write("\t\t\t\t\t\t</dt>\r\n");
      out.write("\t\t\t\t\t\t<dd>\r\n");
      out.write("\t\t\t\t\t\t\t<img class=\"coin11\" src=\"../img/coin111.png\" />\r\n");
      out.write("\t\t\t\t\t\t\t<img class=\"coin22\" src=\"../img/coin222.png\" />\r\n");
      out.write("\t\t\t\t\t\t\t<a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/NewsUrl?op=queryNewsInfo\" target=\"main\"  class=\"cks\">新闻列表</a>\r\n");
      out.write("\t\t\t\t\t\t\t<img class=\"icon5\" src=\"../img/coin21.png\" />\r\n");
      out.write("\t\t\t\t\t\t</dd>\r\n");
      out.write("\t\t\t\t\t</dl>\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t<dl class=\"system_log\">\r\n");
      out.write("\t\t\t\t\t\t<dt>\r\n");
      out.write("\t\t\t\t\t<img class=\"icon1\" src=\"../img/coinL1.png\" /><img class=\"icon2\"\r\n");
      out.write("\t\t\t\t\t\tsrc=\"../img/coinL2.png\" /> 系统管理<img class=\"icon3\"\r\n");
      out.write("\t\t\t\t\t\tsrc=\"../img/coin19.png\" /><img class=\"icon4\"\r\n");
      out.write("\t\t\t\t\t\tsrc=\"../img/coin20.png\" />\r\n");
      out.write("\t\t\t\t       </dt>\r\n");
      out.write("\t\t\t\t\t\t<dd>\r\n");
      out.write("\t\t\t\t\t\t\t<img class=\"coin11\" src=\"../img/coin111.png\" /><img class=\"coin22\" src=\"../img/coin222.png\" />\r\n");
      out.write("\t\t\t\t\t\t\t<a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/admUrl?op=exit\" onclick=\"exit();\" class=\"cks\" target=\"login\">退出</a><img class=\"icon5\" src=\"../img/coin21.png\" />\r\n");
      out.write("\t\t\t\t\t\t</dd>\r\n");
      out.write("\t\t\t\t\t</dl>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t\t<script type=\"text/javascript\">\r\n");
      out.write("\tfunction exit(){\r\n");
      out.write("\t\talert(\"确定退出？！\");\r\n");
      out.write("\t}\r\n");
      out.write("\r\n");
      out.write("\t</script>\r\n");
      out.write("\t\t</body>\r\n");
      out.write("\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
