/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.0
 * Generated at: 2019-07-04 07:38:16 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.backstage;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class log_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP 只允许 GET、POST 或 HEAD。Jasper 还允许 OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=utf-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD XHTML 1.0 Transitional//EN\" \"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd\">\r\n");
      out.write("<html xmlns=\"http://www.w3.org/1999/xhtml\">\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=utf-8\" />\r\n");
      out.write("<title>最强汽修人员登录页面</title>\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"/CarWebPro/backstage/css/public.css\" />\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"/CarWebPro/backstage/css/page.css\" />\r\n");
      out.write("<script type=\"text/javascript\" src=\"/CarWebPro/backstage/js/jquery.min.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"/CarWebPro/backstage/js/public.js\"></script>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("\t<!-- 登录页面头部 -->\r\n");
      out.write("\t<div class=\"logHead\">\r\n");
      out.write("\t\t<img src=\"/CarWebPro/backstage/img/logLOGO.png\" />\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<!-- 登录页面头部结束 -->\r\n");
      out.write("\r\n");
      out.write("\t<!-- 登录body -->\r\n");
      out.write("\r\n");
      out.write("\t<div class=\"logDiv\">\r\n");
      out.write("\t\t<img class=\"logBanner\" src=\"/CarWebPro/backstage/img/logBanner.png\" />\r\n");
      out.write("\t\t<div class=\"logGet\">\r\n");
      out.write("\t\t\t<!-- 头部提示信息 -->\r\n");
      out.write("\t\t\t<div class=\"logD logDtip\">\r\n");
      out.write("\t\t\t\t<p class=\"p1\">登录</p>\r\n");
      out.write("\t\t\t\t<p class=\"p2\">最强汽修人员登录</p>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<!-- 输入框 -->\r\n");
      out.write("\t\t\t<form action=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/admUrl?op=login\" method=\"post\" >\r\n");
      out.write("\t\t\t\t<div class=\"lgD\">\r\n");
      out.write("\t\t\t\t\t<img class=\"img1\" src=\"/CarWebPro/backstage/img/logName.png\" />\r\n");
      out.write("\t\t\t\t\t<input type=\"text\" name=\"adm_name\"  placeholder=\"输入用户名\" />\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"lgD\">\r\n");
      out.write("\t\t\t\t\t<img class=\"img1\" src=\"/CarWebPro/backstage/img/logPwd.png\" />\r\n");
      out.write("\t\t\t\t\t<input type=\"password\" name=\"adm_pwd\"  placeholder=\"输入用户密码\" />\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"logC\">\r\n");
      out.write("\t\t\t\t\t<button type=\"submit\" >登 录</button>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</form>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\r\n");
      out.write("\t<!-- 登录body  end -->\r\n");
      out.write("\r\n");
      out.write("\t<!-- 登录页面底部 -->\r\n");
      out.write("\t<div class=\"logFoot\">\r\n");
      out.write("\t\t<p class=\"p1\">版权所有：最强汽修有限公司</p>\r\n");
      out.write("\t\t<p class=\"p2\">最强汽修科技有限公司 登记序号：渝ICP备11003578号-2</p>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<!-- 登录页面底部end -->\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
